/*
 * generated by Xtext
 */
package rapanui.dsl.ui.contentassist

import rapanui.dsl.ui.contentassist.AbstractMoaiProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MoaiProposalProvider extends AbstractMoaiProposalProvider {
}
