/*
 * generated by Xtext
 */
package rapanui.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DslUiModule extends rapanui.dsl.ui.AbstractDslUiModule {
	public DslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
