/*
 * generated by Xtext
 */
package rapanui.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MoaiUiModule extends rapanui.dsl.ui.AbstractMoaiUiModule {
	public MoaiUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
