/*
 * generated by Xtext
 */
package rapanui.dsl;

import org.eclipse.emf.ecore.EPackage;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MoaiStandaloneSetup extends MoaiStandaloneSetupGenerated{
	@Override
	public void register(Injector injector) {
		// Xcore support as specified at https://bugs.eclipse.org/bugs/show_bug.cgi?id=379999
		EPackage.Registry.INSTANCE.put(DslPackage.eINSTANCE.getNsURI(), DslPackage.eINSTANCE.getNsURI());
		super.register(injector);
	}

	public static void doSetup() {
		new MoaiStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

