/*
 * generated by Xtext
 */
package rapanui.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MoaiStandaloneSetup extends MoaiStandaloneSetupGenerated{

	public static void doSetup() {
		new MoaiStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

