/*
 * generated by Xtext
 */
package rapanui.dsl;

import org.eclipse.xtext.conversion.IValueConverterService;

import rapanui.dsl.conversion.MoaiValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MoaiRuntimeModule extends rapanui.dsl.AbstractMoaiRuntimeModule {
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return MoaiValueConverterService.class;
    }
}
