/*
 * generated by Xtext
 */
package rapanui.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MoaiRuntimeModule extends rapanui.dsl.AbstractMoaiRuntimeModule {

}
